### ISSUE TITLE
cuda runtime error

### ISSUE THREAD

**Issue by yellowtownhz** [gram-ai/capsule-networks#1]
Hello, 
first of all, thx for ur code~
When i tried to run capsule_network.py, i got a runtime error, do u know how to deal with this?
Here is the error:

# parameters: 8215568
Downloading http://yann.lecun.com/exdb/mnist/train-images-idx3-ubyte.gz
Downloading http://yann.lecun.com/exdb/mnist/train-labels-idx1-ubyte.gz
Downloading http://yann.lecun.com/exdb/mnist/t10k-images-idx3-ubyte.gz
Downloading http://yann.lecun.com/exdb/mnist/t10k-labels-idx1-ubyte.gz
Processing...
Done!
  0%|                                           | 1/600 [00:04<42:26,  4.25s/it]THCudaCheck FAIL file=/pytorch/torch/lib/THC/generic/THCStorage.cu line=66 error=2 : out of memory
Traceback (most recent call last):
  File "capsule_network.py", line 259, in <module>
    engine.train(processor, get_iterator(True), maxepoch=NUM_EPOCHS, optimizer=optimizer)
  File "/home/yellowtown/.local/lib/python3.5/site-packages/torchnet/engine/engine.py", line 39, in train
    state['optimizer'].step(closure)
  File "/home/yellowtown/.local/lib/python3.5/site-packages/torch/optim/adam.py", line 39, in step
    loss = closure()
  File "/home/yellowtown/.local/lib/python3.5/site-packages/torchnet/engine/engine.py", line 31, in closure
    loss.backward()
  File "/home/yellowtown/.local/lib/python3.5/site-packages/torch/autograd/variable.py", line 156, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, retain_variables)
  File "/home/yellowtown/.local/lib/python3.5/site-packages/torch/autograd/__init__.py", line 98, in backward
    variables, grad_variables, retain_graph)
  File "/home/yellowtown/.local/lib/python3.5/site-packages/torch/autograd/function.py", line 91, in apply
    return self._forward_cls.backward(self, *args)
  File "/home/yellowtown/.local/lib/python3.5/site-packages/torch/autograd/_functions/blas.py", line 127, in backward
    grad_batch2 = torch.bmm(batch1.transpose(1, 2), grad_output)
  File "/home/yellowtown/.local/lib/python3.5/site-packages/torch/autograd/variable.py", line 584, in bmm
    return self._static_blas(Baddbmm, (output, 0, 1, self, batch), False)
  File "/home/yellowtown/.local/lib/python3.5/site-packages/torch/autograd/variable.py", line 572, in _static_blas
    return cls.apply(*(args[:1] + args[-2:] + (alpha, beta, inplace)))
  File "/home/yellowtown/.local/lib/python3.5/site-packages/torch/autograd/_functions/blas.py", line 107, in forward
    output = _get_output(ctx, add_batch, inplace=inplace)
  File "/home/yellowtown/.local/lib/python3.5/site-packages/torch/autograd/_functions/blas.py", line 13, in _get_output
    return arg.new().resize_as_(arg)
RuntimeError: cuda runtime error (2) : out of memory at /pytorch/torch/lib/THC/generic/THCStorage.cu:66

**Comment by iwasaki-kenta** [comment]
Hi,

For this error, it appears that your graphics card does not have enough memory. How much memory do you have available?

**Comment by yellowtownhz** [comment]
Hi,
The problem is solved when i lower the batchsize,
thx

**Comment by rremani** [comment]
@yellowtownhz  I lowered the batch size to 4 but still getting the error
THCudaCheck FAIL file=/tmp/pip-q7xpozsl-build/torch/lib/THC/generic/THCStorage.cu line=66 error=2 : out of memory
Traceback (most recent call last):
  File "capsule_network.py", line 264, in <module>
    engine.train(processor, get_iterator(True), maxepoch=NUM_EPOCHS, optimizer=optimizer)
  File "/opt/conda/envs/pytorch-py3.6/lib/python3.6/site-packages/torchnet/engine/engine.py", line 39, in train
    state['optimizer'].step(closure)
  File "/opt/conda/envs/pytorch-py3.6/lib/python3.6/site-packages/torch/optim/adam.py", line 52, in step
    state['exp_avg'] = grad.new().resize_as_(grad).zero_()
RuntimeError: cuda runtime error (2) : out of memory at /tmp/pip-q7xpozsl-build/torch/lib/THC/generic/THCStorage.cu:66

I am using Tesla P100 16gb graphic card.

Thanks

**Comment by yellowtownhz** [comment]
Hi, this error accurs because your graphic card doesn't have enough memory avaliable, you can lower the batch size again, or just try run it on another computer?

**Comment by rremani** [comment]
I lowered it to 2 but it's still same. Which graphic card are you using?

**Comment by yellowtownhz** [comment]
gtx1060

**Comment by rremani** [comment]
I have got the same one locally, will try on that too. But 16gb memory should be sufficient with pascal architecture, can you suggest some tinkering in the architecture, which can lower memory usuage? I lowered fc neurons but it didn't  help.

**Comment by yellowtownhz** [comment]
It's weird.Simply lowering the batch size has solved my error before....I can't come up with another better solution either...Maybe you need to check your graphic card's memory first using `nvidia-smi` to make sure you have enough memory,sorry for that~

**Comment by rremani** [comment]
Ya it is weird, ill check the memory. Thanks

**Comment by rremani** [comment]
It's working now, I just had to clean the memory.
